import { expect, test, type Locator, type Page } from "@playwright/test";
import sharp from "sharp";

test.use({ serviceWorkers: "block" });

async function chooseImageTool(page: Page, name: string, menuLabel = "Current image actions") {
  await page.getByRole("button", { name: menuLabel, exact: true }).click();
  await page.getByRole("menuitem", { name, exact: true }).click();
}

async function expectPaletteFillsCard(tools: Locator) {
  const layout = await tools.getByRole("list", { name: "Image colors" }).evaluate(list => {
    const swatches = Array.from(list.querySelectorAll("button"), button => button.getBoundingClientRect());
    const gap = Number.parseFloat(getComputedStyle(list).gap);
    const firstRow = swatches.filter(rect => Math.abs(rect.top - swatches[0].top) < 1);
    const iconGaps = Array.from(list.querySelectorAll("button"), button => {
      const code = button.querySelector(".font-mono")!.getBoundingClientRect();
      const icon = button.querySelector("[data-copy-feedback]")!.getBoundingClientRect();
      return icon.left - code.right;
    });
    return { row: list.getBoundingClientRect().width, widths: swatches.map(rect => rect.width), heights: swatches.map(rect => rect.height), iconGaps, total: firstRow.reduce((width, rect) => width + rect.width, 0) + gap * (firstRow.length - 1) };
  });
  expect(Math.max(...layout.widths) - Math.min(...layout.widths)).toBeLessThan(1);
  expect(Math.abs(layout.total - layout.row)).toBeLessThan(1);
  expect(Math.min(...layout.widths)).toBeGreaterThanOrEqual(44);
  expect(layout.heights.every(height => Math.abs(height - 68) < 1)).toBe(true);
  expect(Math.min(...layout.iconGaps)).toBeGreaterThanOrEqual(4);
}

test("extracts local palettes and real screenshot text with cancellation, retry, and searchable gallery results", async ({ page, context, baseURL }, testInfo) => {
  test.setTimeout(120_000);
  const externalRequests: string[] = [];
  context.on("request", request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(baseURL!).origin && !request.url().startsWith("https://va.vercel-scripts.com/")) externalRequests.push(request.url()); });
  const screenshot = await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="900" height="320"><rect width="900" height="320" fill="white"/><text x="45" y="110" font-family="sans-serif" font-size="58" fill="black">Invoice 4823</text><text x="45" y="205" font-family="sans-serif" font-size="50" fill="black">Total 120 dollars</text><rect x="760" y="30" width="100" height="260" fill="#FF0000"/></svg>')).png().toBuffer();
  await page.goto("/");
  await page.getByRole("button", { name: "Save item", exact: true }).click();
  const capture = page.getByRole("dialog", { name: "Save to Keepall" });
  await capture.locator('input[data-capture-files]').setInputFiles({ name: "receipt.png", mimeType: "image/png", buffer: screenshot });
  await capture.getByRole("textbox", { name: "Optional source URL or caption" }).fill("Receipt screenshot");
  await capture.getByRole("button", { name: "Save", exact: true }).press("Enter");
  await expect(capture).toBeHidden();
  await page.getByRole("link", { name: "Open Receipt screenshot", exact: true }).click();
  const tools = page.getByRole("region", { name: "Image 1 tools" });
  await chooseImageTool(page, "Extract palette");
  const redSwatch = tools.getByRole("button", { name: "Copy color #FF0000", exact: true });
  await expect(redSwatch).toBeVisible();
  await expect(redSwatch).toHaveText("#FF0000");
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  await redSwatch.click();
  await expect(redSwatch.locator("[data-copy-feedback]")).toHaveAttribute("data-copied", "true");
  await expect(tools.getByRole("link")).toHaveCount(0);
  await page.evaluate(() => navigator.clipboard.writeText("Keep clipboard"));
  await redSwatch.click({ button: "right" });
  const colorMenu = page.getByRole("menu", { name: "Color #FF0000", exact: true });
  await expect(colorMenu).toBeVisible();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe("Keep clipboard");
  await expect(colorMenu.getByRole("menuitem", { name: "Search library for nearby colors" })).toHaveAttribute("href", /color%3A%23FF0000/);
  await colorMenu.getByRole("menuitem", { name: "Copy color", exact: true }).click();
  await expect(colorMenu).toBeHidden();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe("#FF0000");
  await redSwatch.focus();
  await redSwatch.press("Shift+F10");
  await expect(colorMenu).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(colorMenu).toBeHidden();
  await expectPaletteFillsCard(tools);
  await expect(tools.locator("p").filter({ hasText: /Copied/ })).toHaveCount(0);

  await context.route("**/ocr/7.0.0/recognize.js", route => route.abort());
  await chooseImageTool(page, "Read text");
  await expect(tools.getByRole("alert")).toContainText("Couldn't load text recognition");
  await context.unroute("**/ocr/7.0.0/recognize.js");
  await page.getByRole("button", { name: "Current image actions", exact: true }).click();
  await expect(page.getByRole("menuitem", { name: "Retry reading text", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await context.route("**/ocr/7.0.0/recognize.js", async route => { await new Promise(resolve => setTimeout(resolve, 1200)); await route.continue(); });
  await chooseImageTool(page, "Read text");
  await tools.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(tools.getByRole("status").filter({ hasText: "Cancelled" })).toBeVisible();
  await context.unrouteAll({ behavior: "wait" });
  await chooseImageTool(page, "Read text");
  await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toContainText(/Invoice 4823/, { timeout: 60_000 });
  await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toContainText(/Total 120 dollars/);
  const copyText = tools.getByRole("button", { name: "Copy text", exact: true });
  await copyText.click();
  await expect(copyText.locator("[data-copy-feedback]")).toHaveAttribute("data-copied", "true");
  await expect(copyText).toHaveText("");
  const paletteToggle = tools.getByRole("button", { name: "Palette", exact: true });
  const textToggle = tools.getByRole("button", { name: "Screenshot text", exact: true });
  const copyBounds = await copyText.boundingBox();
  const textCollapseBounds = await textToggle.boundingBox();
  const paletteCollapseBounds = await paletteToggle.boundingBox();
  expect(copyBounds!.x + copyBounds!.width).toBeLessThan(textCollapseBounds!.x);
  expect(Math.abs(paletteCollapseBounds!.x - textCollapseBounds!.x)).toBeLessThan(1);
  await paletteToggle.click();
  await expect(paletteToggle).toHaveAttribute("aria-expanded", "false");
  await expect(redSwatch).toBeHidden();
  await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toBeVisible();
  await textToggle.click();
  await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toBeHidden();
  await paletteToggle.click();
  await expect(redSwatch).toBeVisible();
  await expect(textToggle).toHaveAttribute("aria-expanded", "false");
  await textToggle.click();
  await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toContainText(/Invoice 4823/);
  await page.reload();
  await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toContainText(/Invoice 4823/);
  await page.screenshot({ path: testInfo.outputPath("image-tools-desktop.png"), fullPage: false });
  await page.setViewportSize({ width: 390, height: 844 });
  await expectPaletteFillsCard(tools);
  await tools.getByRole("heading", { name: "Palette" }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("image-tools-mobile.png"), fullPage: false });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.setViewportSize({ width: 320, height: 740 });
  await expectPaletteFillsCard(tools);
  await tools.getByRole("heading", { name: "Palette" }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("image-tools-small-mobile.png"), fullPage: false });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 900 });
  const secondImage = await sharp({ create: { width: 50, height: 50, channels: 3, background: "#0000FF" } }).png().toBuffer();
  await page.getByLabel("Choose images to add").setInputFiles({ name: "blue.png", mimeType: "image/png", buffer: secondImage });
  const secondTools = page.getByRole("region", { name: "Image 2 tools" });
  await expect(secondTools.getByRole("region", { name: "Extracted text from image 2" })).toHaveCount(0);
  await chooseImageTool(page, "Extract palette");
  await expect(secondTools.getByRole("button", { name: "Copy color #0000FF", exact: true })).toBeVisible();
  await expect(page.getByRole("complementary", { name: "Image details" }).locator("[data-image-tools]")).toHaveCount(0);
  await page.getByRole("button", { name: "Scroll view", exact: true }).click();
  const scrollGallery = page.getByRole("list", { name: "Images in scroll view" });
  await expect(scrollGallery.getByRole("button", { name: "Image 1 actions", exact: true })).toBeVisible();
  await expect(scrollGallery.getByRole("button", { name: "Image 2 actions", exact: true })).toBeVisible();
  await expect(scrollGallery.getByRole("region", { name: "Extracted text from image 1" })).toContainText(/Invoice 4823/);
  await expect(scrollGallery.getByRole("region", { name: "Image 2 tools" }).getByRole("button", { name: "Copy color #0000FF", exact: true })).toBeVisible();
  await chooseImageTool(page, "Refresh palette", "Image 2 actions");
  await expect(scrollGallery.getByRole("region", { name: "Image 2 tools" }).getByRole("status")).toContainText("Palette saved");
  await page.screenshot({ path: testInfo.outputPath("image-tools-scroll-gallery.png"), fullPage: false });
  await scrollGallery.getByRole("button", { name: "Copy color #0000FF", exact: true }).click({ button: "right" });
  await page.getByRole("menu", { name: "Color #0000FF", exact: true }).getByRole("menuitem", { name: "Search library for nearby colors" }).click();
  await expect(page).toHaveURL(/\?q=color%3A%230000FF$/);
  await expect(page.getByRole("link", { name: "Open Receipt screenshot", exact: true })).toBeVisible();
  await page.goto("/?q=color%3Ared%204823");
  await expect(page.getByRole("link", { name: "Open Receipt screenshot", exact: true })).toBeVisible();
  await page.goto("/?q=color%3Ablue%204823");
  await expect(page.getByRole("link", { name: "Open Receipt screenshot", exact: true })).toBeVisible();
  await page.goto("/?q=color%3Agreen%204823");
  await expect(page.getByRole("link", { name: "Open Receipt screenshot", exact: true })).toHaveCount(0);
  expect(externalRequests).toEqual([]);
});

test.describe("OCR offline cache", () => {
  test.use({ serviceWorkers: "allow" });
  test("loads one core on demand and reads a second time offline", async ({ page, context }) => {
    test.setTimeout(120_000);
    const engineRequests: string[] = [];
    context.on("request", request => { if (new URL(request.url()).pathname.startsWith("/ocr/")) engineRequests.push(request.url()); });
    await page.goto("/");
    await page.evaluate(() => navigator.serviceWorker.ready);
    await page.reload();
    await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true);
    expect(engineRequests).toEqual([]);
    const screenshot = await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="180"><rect width="800" height="180" fill="white"/><text x="30" y="110" font-family="sans-serif" font-size="60" fill="black">Offline invoice 7284</text></svg>')).png().toBuffer();
    await page.getByRole("button", { name: "Save item", exact: true }).click();
    const capture = page.getByRole("dialog", { name: "Save to Keepall" });
    await capture.locator('input[data-capture-files]').setInputFiles({ name: "offline.png", mimeType: "image/png", buffer: screenshot });
    await capture.getByRole("textbox", { name: "Optional source URL or caption" }).fill("Offline screenshot");
    await capture.getByRole("button", { name: "Save", exact: true }).press("Enter");
    await expect(capture).toBeHidden();
    await page.getByRole("link", { name: "Open Offline screenshot", exact: true }).click();
    const tools = page.getByRole("region", { name: "Image 1 tools" });
    await chooseImageTool(page, "Read text");
    await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toContainText(/Offline invoice 7284/, { timeout: 60_000 });
    await expect.poll(() => page.evaluate(async () => (await (await caches.open("keepall-ocr-7.0.0")).keys()).length)).toBeGreaterThanOrEqual(5);
    const assets = await page.evaluate(async () => {
      const cache = await caches.open("keepall-ocr-7.0.0");
      return Promise.all((await cache.keys()).map(async request => ({ path: new URL(request.url).pathname, bytes: (await (await cache.match(request))!.arrayBuffer()).byteLength })));
    });
    expect(assets.filter(asset => /core.*wasm\.js$/.test(asset.path))).toHaveLength(1);
    const precachedOcr = await page.evaluate(async () => {
      const names = (await caches.keys()).filter(name => name.includes("precache"));
      const urls = (await Promise.all(names.map(async name => (await (await caches.open(name)).keys()).map(request => request.url)))).flat();
      return urls.filter(url => new URL(url).pathname.startsWith("/ocr/"));
    });
    expect(precachedOcr).toEqual([]);
    console.info(`OCR first-use cached payload: ${assets.reduce((sum, asset) => sum + asset.bytes, 0)} bytes in ${assets.length} local files`);
    await context.setOffline(true);
    await chooseImageTool(page, "Read text again");
    await expect(tools.getByRole("status").filter({ hasText: "Text saved and searchable" })).toBeVisible({ timeout: 60_000 });
    await expect(tools.getByRole("alert")).toHaveCount(0);
    await expect(tools.getByRole("region", { name: "Extracted text from image 1" })).toContainText(/Offline invoice 7284/);
  });
});
