import { SHELL_TOP_BTN, SHELL_TOP_BTN_ACTIVE, SHELL_TOP_BTN_IDLE } from "./shell-styles";

/** Shared by the app and the isolated extension drawer. */
export const captureStyles = {
  header: "flex shrink-0 items-start gap-4 px-7 py-6",
  heading: "min-w-0 flex-1",
  title: "[overflow-wrap:anywhere] text-[22px] font-semibold tracking-tight",
  description: "mt-1 [overflow-wrap:anywhere] text-sm leading-relaxed text-text-secondary",
  close: "ui-control flex size-10 shrink-0 items-center justify-center disabled:cursor-not-allowed disabled:opacity-50",
  form: "flex min-h-0 flex-1 flex-col overflow-hidden",
  body: "flex flex-col gap-4 px-6 pb-5 pt-3",
  footer: "flex shrink-0 flex-wrap items-center justify-end gap-2 border-t border-border-control bg-bg-canvas px-6 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-5",
  primary: `${SHELL_TOP_BTN} ${SHELL_TOP_BTN_ACTIVE} px-4 disabled:opacity-60`,
  secondary: `${SHELL_TOP_BTN} ${SHELL_TOP_BTN_IDLE} px-4 disabled:opacity-60`,
  "bulk-import": `${SHELL_TOP_BTN} ${SHELL_TOP_BTN_IDLE} mr-auto px-3 text-xs disabled:opacity-60`,
  "file-add": `${SHELL_TOP_BTN} ${SHELL_TOP_BTN_IDLE} h-8 px-3 text-xs disabled:opacity-60`,
  "footer-hint": "order-first basis-full text-xs text-text-secondary",
  "note-editor": "flex flex-col gap-3",
  "note-head": "flex flex-wrap items-center justify-between gap-2",
  "field-label": "text-sm font-medium text-text-primary",
  "note-input": "ui-field min-h-28 resize-y px-3 py-2 text-sm",
  "note-preview": "flex min-h-0 max-h-36 shrink-0 flex-col rounded-input border border-border-control bg-bg-control h-28 overflow-auto p-4",
  "org-panel": "flex flex-col gap-4 py-1",
  "org-section": "flex flex-col gap-2 rounded-panel border border-border-control p-3",
  "org-head": "flex min-h-6 items-center justify-between gap-3",
  "org-title": "flex items-center gap-2 text-sm font-semibold text-text-primary",
  "browse-trigger": "min-h-7 rounded-control px-2 text-xs font-medium text-text-secondary hover:bg-bg-raised hover:text-text-primary",
  "org-search-wrap": "flex min-h-7 min-w-0 items-center gap-2 text-text-secondary focus-within:text-text-primary",
  "org-search": "min-h-7 min-w-0 flex-1 bg-transparent text-sm text-text-primary outline-none placeholder:text-text-secondary disabled:opacity-60",
  choice: "control-squircle squircle-panel inline-flex min-h-7 max-w-full shrink-0 items-center gap-1 rounded-control border px-2 py-0.5 text-xs disabled:opacity-60",
  "choice-idle": "border-border-control bg-bg-control text-text-secondary hover:bg-bg-raised hover:text-text-primary",
  "choice-selected": "border-border-control bg-bg-active text-text-primary",
  "remove-tag": "flex size-6 shrink-0 items-center justify-center rounded-control text-text-secondary hover:bg-bg-danger hover:text-text-danger disabled:opacity-60",
  browse: "confirm-dialog-popup ui-popover flex h-[min(80dvh,36rem)] w-full max-w-[28rem] flex-col overflow-hidden p-0 outline-none",
  "browse-header": "flex shrink-0 items-start gap-4 border-b border-border-control px-5 py-4",
  "browse-search": "ui-field h-11 w-full ps-10 pe-3 text-sm",
  "browse-option": "ui-menu-item flex w-full items-center justify-between text-start text-sm",
  "file-list": "divide-y divide-border-control",
  "file-row": "flex items-center gap-3 py-2",
  "file-icon": "flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-bg-raised",
  "file-thumbnail": "media-outline size-full object-cover",
  "file-name": "min-w-0 flex-1",
  "file-title": "break-all text-sm font-medium",
  "file-status": "mt-1 text-xs text-text-secondary",
  "file-remove": "ui-control flex size-8 shrink-0 items-center justify-center",
  "browse-heading": "min-w-0 flex-1",
  "browse-title": "text-lg font-semibold text-text-primary",
  "browse-description": "mt-1 text-sm text-text-secondary",
  "browse-selected": "text-xs text-text-secondary",
  "browse-empty": "px-3 py-8 text-center text-sm text-text-secondary",
  "choice-label": "truncate",
  "selected-tags": "flex flex-wrap gap-1.5",
  "choices": "flex flex-wrap gap-1.5 overflow-hidden max-h-[3.875rem]",
  "file-add-control": "flex flex-wrap items-center gap-x-3 gap-y-2",
  "file-staging": "flex flex-col gap-4",
  "file-details": "flex flex-col gap-4",
  "file-layout": "flex flex-wrap gap-2",
  "file-actions": "flex flex-wrap gap-2",
  "file-progress": "text-sm text-text-secondary",
  "note-help": "text-xs text-text-secondary [overflow-wrap:anywhere]",
  "org-status": "text-sm text-text-secondary",
  "error": "text-sm text-text-danger",
  "field": "flex flex-col gap-2",
  "org-create": "ui-control inline-flex min-h-9 max-w-full items-center gap-2 self-start px-3 py-1.5 text-left text-xs font-medium disabled:opacity-60",
  "discard-draft": "ui-control px-3 py-1 text-xs",
  "browse-close": "ui-control flex size-10 shrink-0 items-center justify-center",
} as const;
