import pdfImage from "../../../public/marketing/app-pdf-reader.webp";
import markdownImage from "../../../public/marketing/app-markdown-document.webp";
import previewImage from "../../../public/marketing/app-preview-document.webp";
import searchImage from "../../../public/marketing/app-search-files.webp";
import noteImage from "../../../public/help/note-editor.webp";
import type { Guide } from "./guides";

export const focusedGuides: Guide[] = [
  {
    slug: "search", category: "Find your saves", title: "Search your library",
    summary: "Find words in notes, saved articles, documents, and recognized screenshot text.", minutes: "3 min read",
    sections: [
      { id: "words", title: "Search words across your saves", paragraphs: ["Use the library search box to find titles, notes, captions, source addresses, filenames, tags, and saved article text. PDF search reads selectable text. Text recognized with Read text is searchable too. Video sound and scanned PDF page images are not searchable.", "Every word must match the item, but the words can appear in different fields. Searching recipe dinner can match recipe in a title and dinner in its note. Search ignores letter case. Put words in double quotes, such as \"garden plan\", to find that phrase together.", "Results highlight matching words and show excerpts labelled with their source, such as File contents, My note, Saved article, or Image text. Choose Best match in the sort menu to put stronger matches first. A title match ranks above a mention in a source address."], visual: { kind: "image", src: searchImage.src, width: searchImage.width, height: searchImage.height, alt: "Library search results with highlighted file content and recognized image text", caption: "Excerpts show where a word was found, including inside a saved file." } },
      { id: "scope", title: "Check where you are searching", paragraphs: ["Search stays within your current collection, tag, and item-type filters. If the results look incomplete, check the scope above them. Clear filters removes search and type filters while keeping your current destination. When offered, Search entire library keeps your search words and broadens the search beyond the current collection or tag.", "All collections and All tags search collection or tag names. Open a collection or tag to search the saved items inside it. Trash has its own search. Normal library results exclude items in Trash.", "Pinned items stay first inside a collection. Best match is available while searching; clearing the search returns to newest first if Best match was selected."], links: [{ label: "Organize with collections and tags", href: "/help/collections-and-tags" }, { label: "Restore an item from Trash", href: "/help/collections-and-tags#trash" }] },
      { id: "colors", title: "Find an image by color", paragraphs: ["Search color:red for a color family, or color:#FF0000 for nearby shades of a specific hex color. Add words to narrow it further, such as color:red receipt. All terms must match.", "Only images with an extracted palette can match a color search. Open an image's menu and choose Extract palette first. Unknown color names return no matches. color: is the only query operator; searches do not support OR, exclusions, or type: syntax."], links: [{ label: "Extract and copy a palette", href: "/help/images-and-videos#palette" }] },
      { id: "file-search", title: "Give file searches time to finish", paragraphs: ["Keepall reads saved document contents locally while searching. Large files and libraries can take longer. Search reads the saved file beyond the shortened reading preview. If some file text could not be searched, choose Retry search.", "A scanned PDF can still be viewed, but Keepall does not recognize text in its page images. For screenshot text, run Read text on the saved image, review the result, then search its words."], links: [{ label: "Read and search documents", href: "/help/documents#search-and-backups" }, { label: "Recognize screenshot text", href: "/help/images-and-videos#image-text" }] },
    ], action: { label: "Search your library", href: "/" },
  },
  {
    slug: "documents", category: "Reading", title: "Read PDFs, Markdown and text files",
    summary: "Bring local files into your library, read them, and keep your own notes beside them.", minutes: "4 min read",
    sections: [
      { id: "import", title: "Bring in a document", paragraphs: ["Imported TXT and Markdown files appear in the Notes filter alongside standalone notes. The Documents filter includes document items, including imported TXT, Markdown, and PDF files."], steps: ["Open Save item and choose Add files. For many files or a folder, choose Bulk import instead.", "Choose UTF-8 .txt or .md files up to 10 MiB each, or a PDF up to 50 MiB and 1,000 pages. Password-protected PDFs need an unlocked copy.", "Choose a collection and tags, then Save. Open the item's menu and choose Open full item to read its saved copy. If some files fail to save, Retry failed files keeps the ones already saved."], links: [{ label: "Import multiple files or a folder", href: "/help/import#images" }] },
      { id: "pdf", title: "Read a PDF at your own pace", paragraphs: ["Choose Pages to read one page at a time, or Scroll to move through the whole document. Previous page and Next page move between pages. Type a page number in the Page field and press Enter to jump there.", "Use the zoom menu to choose Fit width or a percentage from 75% to 200%. You can select text when the PDF contains a text layer. Scanned pages are viewable, but scanned-PDF text recognition is unavailable."], visual: { kind: "image", src: pdfImage.src, width: pdfImage.width, height: pdfImage.height, alt: "A saved PDF with Pages and Scroll controls, page navigation, and a zoom menu", caption: "Page navigation and zoom stay above the locally saved PDF." } },
      { id: "text-and-markdown", title: "Read or edit text and Markdown", paragraphs: ["Text files show their saved text. Markdown files render headings, lists, tables, code, and other supported formatting. Imported Markdown does not load remote images or embedded HTML.", "Choose Edit to change the saved text. Saving edits changes Keepall's copy; the original file on your device stays unchanged. Long reading previews stop at 200,000 characters. Download file gives you the full saved file, including edits."], visual: { kind: "image", src: markdownImage.src, width: markdownImage.width, height: markdownImage.height, alt: "A Markdown document rendered with headings, a table, and formatted text", caption: "Keepall renders imported Markdown using its own reading layout." }, links: [{ label: "Write a standalone note with local images", href: "/help/notes" }] },
      { id: "personal-notes", title: "Keep your thoughts beside the file", paragraphs: ["Use Edit to add a personal note separate from the document's contents. You can format that note as plain text or Markdown. Changing a PDF's title or personal note leaves its file unchanged.", "Choose Download file on the full item page to keep another copy of the saved document."], links: [{ label: "Browse document previews", href: "/help/preview#content" }] },
      { id: "search-and-backups", title: "Find file text and keep a backup", paragraphs: ["Library search finds words in the title, filename, tags, personal note, and saved file contents. TXT and Markdown search includes text beyond the shortened preview. PDF search reads selectable text, so a scanned page needs a text layer to match.", "File viewing, editing, and search run on your device. Keepall backups include saved documents and their edits. Export a backup before clearing browser data or moving your library."], links: [{ label: "Search your library", href: "/help/search" }, { label: "Back up your files", href: "/help/storage-and-backups#download" }] },
    ], action: { label: "Open your library", href: "/" },
  },
  {
    slug: "preview", category: "Browsing", title: "Browse without losing your place",
    summary: "Move through saves in a quick preview, then open the full item when you want more.", minutes: "3 min read",
    sections: [
      { id: "open", title: "Preview the results in front of you", paragraphs: ["Choose Preview beside the grid and list controls to browse your current collection, tag, or search results. It starts at the last focused item, or the first result. To begin with a particular save, open its three-dot menu or right-click it and choose Preview.", "Preview is for browsing saved items. Fetch preview or Refresh preview in a link's menu requests a title, description, and cover from the website while online. Save for offline or Update saved article keeps readable article text for the full item page."], visual: { kind: "image", src: previewImage.src, width: previewImage.width, height: previewImage.height, alt: "A document quick preview with Back, Next, and Open full item controls over the library", caption: "Quick preview keeps the current results behind the item you are reading." } },
      { id: "keyboard", title: "Move through your saves", paragraphs: ["Use Back and Next in preview to move in the current result order. In the library, use Tab to focus a card or row, then arrow keys to browse. Space opens quick preview by default. Arrows keep browsing while preview stays open. Shift plus an arrow extends a library selection.", "Escape closes preview and returns focus to the last previewed item. Enter opens its full page, or choose Open full item. A link's title can open its original website; use the item menu's Open full item to reach saved details and articles.", "You can change Preview results and other app shortcuts in Settings, General, App shortcuts. If you change Space, use your assigned shortcut instead."], links: [{ label: "Read a saved article", href: "/help/saved-articles#read" }] },
      { id: "content", title: "Read notes, files, images, and local videos", paragraphs: ["Notes and documents are readable inside preview. Local video files have playback controls. For an image, choose Fit to see the whole image or Scroll to read a long screenshot at the available width. Image notes scroll separately below the media.", "Gallery buttons move between images within one item. Back and Next move between saved items. A link's quick preview shows its cover, description, source, and personal note. Read the saved article on its full item page."], links: [{ label: "Read document files", href: "/help/documents" }, { label: "Play a saved video", href: "/help/images-and-videos#videos" }] },
      { id: "list", title: "Choose how much to see in the list", paragraphs: ["Switch between Grid and List beside Preview. In List, open List columns and choose Auto, 1 column, 2 columns, or 3 columns. Auto adjusts the layout to the available width. The same search and collection scope stay in place when you change views."] },
    ], action: { label: "Browse your library", href: "/" },
  },
  {
    slug: "notes", category: "Writing", title: "Write notes with text and images",
    summary: "Keep a plain note or use Markdown for headings, tables, code, and locally saved images.", minutes: "3 min read",
    sections: [
      { id: "write", title: "Start with your own words", paragraphs: ["Open Save item and write a note without a link or media file. Add a title, collection, and tags if useful, then Save. Open the note's menu and choose Edit to return to it.", "Notes start as plain text. Turn on Markdown for formatting. Choose Preview to read the result, then Edit to keep writing. Save your changes before closing the editor."], visual: { kind: "image", src: noteImage.src, width: noteImage.width, height: noteImage.height, alt: "The note editor with Markdown, Edit and Preview controls and an attached local image", caption: "The editor lets you check formatting and place images between paragraphs." } },
      { id: "format", title: "Use Markdown when structure helps", paragraphs: ["Write # before a heading, - before a list item, or numbers such as 1. for an ordered list. Use **text** for bold, *text* for emphasis, and backticks around inline code. Fenced code blocks and Markdown tables are supported too.", "Markdown checklists display checked or unchecked boxes. They are read-only in the rendered note; change the Markdown in Edit to update them. Preview shows how the saved note will read."] },
      { id: "images", title: "Place a local image in the note", paragraphs: ["When editing a standalone note, place the cursor between paragraphs and choose Add image at cursor. Select an image from your device. The editor inserts it at that position and lists the attached images below the controls. Switch back to Edit if you are in Preview.", "Use Remove beside an attached image to remove it from the note, then save your changes. Attached images are stored locally and included in Keepall backups. They are separate from remote image links in imported Markdown, which Keepall does not load."], links: [{ label: "Supported image files and limits", href: "/help/images-and-videos#images" }, { label: "Read imported Markdown files", href: "/help/documents#text-and-markdown" }] },
      { id: "personal-notes", title: "Add context to another save", paragraphs: ["Links, images, videos, and documents can have a personal note too. Use the item's Edit action to record why you saved it or what you want to remember. Plain text and Markdown are available for these notes.", "A personal note stays separate from a saved article or document's contents. Search finds its words along with the item. Local image attachments belong to standalone notes."], links: [{ label: "Search your notes", href: "/help/search" }] },
    ], action: { label: "Write a note", href: "/" },
  },
];
